### ISSUE TITLE
cannot properly build and install into home directory only

### ISSUE THREAD

**Issue by ccaudle** [bruno-unna/euclidean-rhythms#10]
See question in discussion page.  
When following instructions in readme.md:
meson setup --native-file=environments/linux64.ini --libdirbuilddir=/home/chris/.lv2
cd builddir
meson install

There is still a prompt for elevated privilege.

This is the output of the meson configure step:

The Meson build system
Version: 1.0.0
Source dir: /home/chris/Src/EuclideanLV2/euclidean-rhythms
Build dir: /home/chris/Src/EuclideanLV2/euclidean-rhythms/builddir
Build type: native build
WARNING: failed to process netrc file: ~/.netrc access too permissive: access permissions must restrict access to only the owner (None, line None).
Project name: euclidean.lv2
Project version: 0.2.0-SNAPSHOT
C compiler for the host machine: ccache cc (gcc 12.2.1 "cc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)")
C linker for the host machine: cc ld.bfd 2.38-25
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency lv2 found: YES 1.18.8
Library m found: YES
Program git found: YES (/usr/bin/git)
Configuring manifest.ttl using configuration
Configuring euclidean.ttl using configuration
Dependency lv2 found: YES 1.18.8 (cached)
WARNING: Library target 'euclidean' has 'name_prefix' set. Compilers may not find it from its '-leuclidean' linker flag in the 'euclidean.pc' pkg-config file.
WARNING: Library target 'euclidean' has 'name_prefix' set. Compilers may not find it from its '-leuclidean' linker flag in the 'euclidean-uninstalled.pc' pkg-config file.
Build targets in project: 3

euclidean.lv2 0.2.0-SNAPSHOT

  User defined options
    Native files: environments/linux64.ini
    libdir      : /home/chris/.lv2

Found ninja-1.10.2 at /usr/bin/ninja

$ meson install
ninja: Entering directory `/home/chris/Src/EuclideanLV2/euclidean-rhythms/buildd
ir'
[8/8] Linking target test/test_euclidean
Installing src/**euclidean.so** to /home/chris/**.lv2/lv2/euclidean.lv2**
Installing /home/chris/Src/EuclideanLV2/euclidean-rhythms/include/**euclidean.h** to
 /**usr**/local/include/
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
Error executing command as another user: Not authorized

When running in a desktop environment I get a pop-up asking for sudo password, when running in just a bash shell through ssh I do not even get a request for password, which may just be a polkit configuration problem.

Note the line about installing euclidean.so: In my ~/.lv2 directory instead of a euclidean.lv2 directory, there is lv2/euclidean.lv2 which seems to mean that the build script is attempting to install into $libdir/lv2/euclidean.lv2, which does not match with the instructions to set libdir to ~/.lv2 in the "how to build" section.

In the ~/.lv2/lv2/euclidean.lv2 directory after the install command I find euclidean.so but no ttl files, so the plugin is not actually usable at that point.

Why is the install script attempting to copy the plugin header file to /usr/local/include?  You should never need a .h file installed just to run a LV2 plugin.

I am not familiar with meson, but if someone can give some pointers to where I could learn about meson configuration files and a quick start guide or similar, I can try to figure out what is incorrect and submit a pull request to address.

**Comment by bruno-unna** [comment]
Thank you for the detailed report.

As you surely have already guessed, I'm not familiar with meson either. But I think I've a solution for this issue. It's already documented in the README file, but in a nutshell: use the option `--libdir` for the first step (I think I've fixed it). For example, if you home directory is `/home/chris`, you could use 
`--libdir=/home/chris/.lv2`. For the moment, there are two caveats:
- The directory needs to end in `.lv2` for this to work.
- The directory has to be explicitly stated, the special `~` can't be used.

Please try that and let me know if that works.

PS: I also removed the installation of the header file. That was a slip on my part.

**Comment by ccaudle** [comment]
Built, installed, and added to a track. Now I just need some time to play with it and make some noises.
