### ISSUE TITLE
Incorrect test causes non-x86 arch build to fail

### ISSUE THREAD

**Issue by Baggypants** [bruno-unna/euclidean-rhythms#11]
if Arch isn't x86 or x86_64 then lib_c_args isn't defined causeing the build to fail.

[src](https://github.com/bruno-unna/euclidean-rhythms/tree/develop/src/meson.build)

```meson.build
# Add default x86 and x86_64 optimizations
if current_arch == 'x86' or current_arch == 'x86_64' and current_os != 'darwin'
    lib_c_args = ['-msse','-msse2','-mfpmath=sse','-ffast-math','-fomit-frame-pointer','-fno-finite-math-only']
endif
```

should be

```meson.build
# Add default x86 and x86_64 optimizations
if current_arch == 'x86' or current_arch == 'x86_64' and current_os != 'darwin'
    lib_c_args = ['-msse','-msse2','-mfpmath=sse','-ffast-math','-fomit-frame-pointer','-fno-finite-math-only']
else
    lib_c_args = ''
endif
```

Or something.

**Comment by bruno-unna** [comment]
Thanks for detecting and providing a solution, @Baggypants. I've made a change very similar to what you suggest, but I've no way to test it. Do you have a non-x86 architecture to validate the fix?

**Comment by bruno-unna** [comment]
Sorry, hit the wrong button and closed the issue, but reopened it until the fix is validated.

**Comment by Baggypants** [comment]
This fix allows the build to continue. It doesn't build but I don't know meson to troubleshoot it.

**Comment by bruno-unna** [comment]
> This fix allows the build to continue. It doesn't build but I don't know meson to troubleshoot it.

Oh, that's bad news. Sorry to hear that.

Unfortunately, I don't know meson myself (I've learnt the little I know just for this project), and even worse: I don't have access to any machine which is not x86. If you feel so inclined, we could work together to make it work in your machine, but be aware that you're **not** dealing with an expert.

**Comment by bruno-unna** [comment]
Closing the issue for lack of feedback.
